Repository ckan/ckan, pull requests merged in 2018-10, with the labels that each got.

#4495 Register multiple blueprints for each plugin
  ckan/config/middleware/flask_app.py
Labels: Backport 2.7.5, Backport 2.8.2, Backport pending

#4476 Replace request.{POST->form} and non-initialized vars
  ckan/tests/controllers/test_package.py
  ckan/views/resource.py
Labels: Pylons - Flask migration

#4506 Fix organization and group image uploads
  ckan/views/group.py
Labels: Pylons - Flask migration

#4521 Allow to define legacy route mappings as a dict in config
  ckan/lib/helpers.py
  ckan/tests/controllers/test_home.py
Labels: Backport 2.8.2, Backport pending
