Repository ckan/ckan, pull requests merged in 2018-06, with the labels that each got.

#4274 [#4255] docs use current version
  doc/conf.py
  doc/maintaining/installing/install-from-docker-compose.rst
Labels: Backport 2.5.10, Backport 2.6.7, Backport 2.7.5, Backport 2.8.1, Backport pending

#4276 [#4272]fix icon
  ckan/templates-bs2/snippets/license.html
  ckan/templates/snippets/license.html
Labels: Backport 2.8.1, Backport pending

#4281 Remove overly-specific .site-search input border
  ckan/public/base/less/masthead.less
Labels: Backport 2.8.1, Backport pending

#4257 Error handler update
  ckan/config/middleware/flask_app.py
  ckan/views/api.py
Labels: Backport 2.8.1, Pylons - Flask migration

#4293 Speed up sphinx test
  ckan/tests/test_coding_standards.py
  dev-requirements.txt
Labels: To Discuss

#4312 Translate strings in macro custom
  ckan/templates-bs2/macros/form.html
  ckan/templates/macros/form.html
Labels: Backport 2.8.1, Backport pending
