Repository ckan/ckan, pull requests merged in 2018-07, with the labels that each got.

#4349 [#4303] Update error handler
  ckan/config/middleware/flask_app.py
Labels: Backport 2.8.1, Backport pending, Pylons - Flask migration

#4350 [#4260] 'New view' button fix
  ckan/templates-bs2/package/resource_views.html
Labels: Backport 2.8.1, Backport pending

#4348 [#4346] Update missing legacy routes
  ckan/lib/helpers.py
Labels: Backport 2.8.1, Backport pending, Pylons - Flask migration

#4288 Validation Error on datastore_search when sorting timestamp fields
  ckanext/datastore/backend/postgres.py
  ckanext/datastore/tests/test_search.py
Labels: Backport 2.7.5, Backport 2.8.1, Backport pending

#4307 Don't explode when a non-logged in user visits /dashboard
  ckan/tests/controllers/test_user.py
  ckan/views/dashboard.py
Labels: Backport pending

#4360 Translate search facets only if they are present
  ckanext/multilingual/plugin.py
Labels: Backport 2.8.1, Backport pending

#4319 [#4310] Add global properties `controller` and `action`
  CHANGELOG.rst
  ckan/config/middleware/flask_app.py
  ckan/plugins/toolkit.py
  ckan/views/__init__.py
Labels: Backport 2.8.1, Backport pending
