Repository ckan/ckan, pull requests merged in 2018-04, with the labels that each got.

#4158 Fix datastore dump > 25k records
  ckanext/datastore/controller.py
Labels: Backport 2.7.3, Backport pending, Pending 2.8.0

#4144 commented statement in legacy test for coding standards
  ckan/tests/legacy/functional/api/model/test_licenses.py
  ckan/tests/legacy/test_coding_standards.py
Labels: Pending 2.8.0

#4163 [#4161] fix datastore info test, move to extension
  ckan/tests/controllers/test_api.py
  ckanext/datastore/tests/helpers.py
  ckanext/datastore/tests/test_chained_action.py
  ckanext/datastore/tests/test_chained_auth_functions.py
  ckanext/datastore/tests/test_create.py
  ckanext/datastore/tests/test_db.py
  ckanext/datastore/tests/test_delete.py
  ckanext/datastore/tests/test_dump.py
  ckanext/datastore/tests/test_helpers.py
  ckanext/datastore/tests/test_info.py
  ckanext/datastore/tests/test_interface.py
  ckanext/datastore/tests/test_plugin.py
  ckanext/datastore/tests/test_search.py
  ckanext/datastore/tests/test_upsert.py
Labels: Pending 2.8.0

#4145 increase the strength of the password reset token
  ckan/lib/mailer.py
Labels: Pending 2.8.0

#4169 Fix Add Member form column display
  ckan/public/base/less/forms.less
  ckan/templates/group/member_new.html
  ckan/templates/organization/member_new.html
Labels: Pending 2.8.0

#4173 Refactor Password Reset templates by adding missing Bootstrap 3 markup
  ckan/templates/user/perform_reset.html
  ckan/templates/user/request_reset.html
Labels: Pending 2.8.0

#4174 Fix limited width of Order by select element
  ckan/public/base/less/search.less
Labels: Pending 2.8.0

#4181 DataStore Map preview does not show plot markers
  ckanext/reclineview/theme/public/recline_view.js
Labels: Backport pending, Pending 2.8.0

#4167 [#4142] rest api docs update
  doc/api/legacy-api.rst
Labels: Pending 2.8.0

#4196 [#4160] fix language switcher
  ckan/public-bs2/base/javascript/plugins/jquery.images-loaded.js
  ckan/public-bs2/base/javascript/resource.config
  ckan/public/base/javascript/plugins/jquery.images-loaded.js
  ckan/public/base/javascript/resource.config
Labels: Pending 2.8.0

#4197 Install setuptools recommended version as part of the Docker build
  Dockerfile
Labels: Backport 2.7.4, Backport pending, Pending 2.8.0

#4199 fix failing test on dev-2.8 build
  ckan/tests/test_none_root.py
Labels: Pending 2.8.0

#4208 [#3567] Fix feed URL in group and org pages
  ckan/templates-bs2/group/snippets/feeds.html
  ckan/templates-bs2/organization/snippets/feeds.html
  ckan/templates/group/snippets/feeds.html
  ckan/templates/organization/snippets/feeds.html
Labels: Backport 2.7.4, Backport pending, Pending 2.8.0

#4207 [#4031] More support for custom group types in templates
  ckan/templates-bs2/group/snippets/group_form.html
  ckan/templates-bs2/organization/snippets/organization_form.html
  ckan/templates/group/snippets/group_form.html
  ckan/templates/organization/snippets/organization_form.html
  ckan/templates/package/base.html
  ckanext/example_igroupform/tests/test_controllers.py
Labels: Pending 2.8.0
