Repository ckan/ckan, pull requests merged in 2018-05, with the labels that each got.

#4223 Remove Jinja2 Bytecode cache
  ckan/lib/jinja_extensions.py
Labels: Pending 2.8.0, To Discuss

#4231 [#4209] Changes needed for new stable docs URLs
  ckan/lib/app_globals.py
  doc/contributing/release-process.rst
Labels: Backport 2.5.9, Backport 2.6.6, Backport 2.7.4, Backport pending, Pending 2.8.0

#4225 403 exceptions with flask
  ckan/config/middleware/flask_app.py
  ckan/controllers/error.py
  ckan/templates-bs2/error_document_template.html
  ckan/templates/error_document_template.html
  ckan/tests/controllers/test_feed.py
  ckan/tests/controllers/test_user.py
Labels: Pending 2.8.0, Pylons - Flask migration

#4234 Update labelText in resource-view-reorder module
  ckan/public-bs2/base/javascript/modules/resource-view-reorder.js
Labels: Pending 2.8.0

#4241 Add missing CSS class to modal title in resource_view.html
  ckan/templates/package/snippets/resource_view.html
Labels: Pending 2.8.0

#4242 Add missing CSS class to Fullscreen and Embed buttons
  ckan/public/base/less/resource-view.less
  ckan/templates/package/snippets/resource_view.html
Labels: Pending 2.8.0

#4230 Fix display of org title in organization stream
  ckan/lib/helpers.py
Labels: Backport 2.5.9, Backport 2.6.6, Backport 2.7.4, Backport pending, Pending 2.8.0

#4232 Show warning on unsupported, old or latest docs
  dev-requirements.txt
  doc/_static/ckanlogo.png
  doc/_static/css/custom.css
  doc/_templates/layout.html
  doc/conf.py
Labels: Backport 2.5.9, Backport 2.6.6, Backport 2.7.4, Backport pending, Pending 2.8.0

#4265 Upload logo fix
  ckan/views/admin.py
Labels: Backport 2.8.1, Backport pending, Pylons - Flask migration
