Repository ckan/ckan, pull requests merged in 2018-03, with the labels that each got.

#4050 [#4044] Pylons and Flask just use the same options for Jinja2 environment
  ckan/config/environment.py
  ckan/config/middleware/flask_app.py
  ckan/lib/jinja_extensions.py
  ckan/lib/render.py
  ckan/tests/controllers/test_api.py
  ckanext/example_flask_iblueprint/plugin.py
  ckanext/example_flask_streaming/plugin.py
Labels: Pylons - Flask migration

#3891 rewrite home blueprint
  ckan/config/routing.py
  ckan/lib/helpers.py
  ckan/templates-bs2/header.html
  ckan/templates-bs2/snippets/home_breadcrumb_item.html
  ckan/templates/header.html
  ckan/templates/home/about.html
  ckan/templates/snippets/home_breadcrumb_item.html
  ckan/tests/config/test_middleware.py
  ckan/tests/controllers/test_home.py
  ckan/views/home.py
  ckanext/example_itranslation/tests/test_plugin.py
Labels: Pylons - Flask migration

#4063 [#4042] update extras only for deleted resource
  ckanext/datastore/plugin.py
  ckanext/datastore/tests/test_delete.py
Labels: Backport 2.7.3, Backport pending

#4082 [#4081] Return a 403 if not authorized on the search page
  ckan/controllers/package.py
Labels: Backport 2.5.8, Backport 2.6.5, Backport 2.7.3, Backport pending

#4100 [#4094] Update Orgs/Groups logic for custom fields delete and update
  ckan/lib/dictization/model_save.py
Labels: Backport 2.5.8, Backport 2.6.5, Backport 2.7.3, Backport pending

#4141 [#4140] Fix URL for datastore_search action provided when adding filter
  ckan/public-bs2/base/javascript/modules/resource-view-filters.js
  ckan/public/base/javascript/modules/resource-view-filters.js
Labels: Backport pending

#4156 Add missing empty space between "Add to group" button
  ckan/public/base/less/forms.less
  ckan/public/base/less/module.less
Labels: Pending 2.8.0
