Repository ckan/ckan, pull requests merged in 2018-08, with the labels that each got.

#4380 [#4379] Fix edit slug button
  ckan/public/base/javascript/plugins/jquery.slug-preview.js
Labels: Backport 2.8.2, Backport pending

#4414 Don't re-register plugin helpers on flask_app, as it has been done on load_environment
  ckan/config/middleware/flask_app.py
Labels: Backport 2.7.5, Backport 2.8.2, Backport pending, Pylons - Flask migration

#4426 Flask patch update
  requirements.in
  requirements.txt
Labels: Backport 2.7.5, Backport 2.8.2
