Repository ckan/ckan, pull requests merged in 2019-05, with the labels that each got.

#4756 Fix to allow multiple tags in a single dataset search
  ckan/lib/helpers.py
  ckan/tests/controllers/test_package.py
  ckan/views/dataset.py
Labels: Backport pending

#4769 Facet filtering does not work in 'group.read' or 'organization.read' pages
  ckan/views/group.py
Labels: Backport pending

#4712 CLI. Implement `datastore` command
  ckan/cli/cli.py
  ckan/cli/datastore.py
Labels: Pylons - Flask migration

#4708 CLI. Implement `dataset` command
  ckan/cli/cli.py
  ckan/cli/dataset.py
Labels: Pylons - Flask migration

#4707 CLI. Implement `datapusher` command
  ckan/cli/cli.py
  ckan/cli/datapusher.py
Labels: Pylons - Flask migration

#4614 Webassets
  ckan/cli/asset.py
  ckan/cli/cli.py
  ckan/config/deployment.ini_tmpl
  ckan/config/environment.py
  ckan/config/middleware/flask_app.py
  ckan/lib/extract.py
  ckan/lib/helpers.py
  ckan/lib/jinja_extensions.py
  ckan/lib/webassets_tools.py
  ckan/plugins/toolkit.py
  ckan/public/base/css/webassets.yml
  ckan/public/base/javascript/apply-html-class.js
  ckan/public/base/javascript/modules/resource-reorder.js
  ckan/public/base/javascript/resource.config
  ckan/public/base/javascript/webassets.yml
  ckan/public/base/vendor/resource.config
  ckan/public/base/vendor/webassets.yml
  ckan/templates/base.html
  ckan/templates/package/new_resource.html
  ckan/templates/package/resource_edit_base.html
  ckan/templates/package/resource_views.html
  ckan/templates/package/resources.html
  ckan/templates/page.html
  ckan/tests/test_none_root.py
  ckanext/datatablesview/public/resource.config
  ckanext/datatablesview/public/webassets.yml
  ckanext/datatablesview/templates/datatables/datatables_view.html
  ckanext/example_theme_docs/v15_fanstatic/fanstatic/webassets.yml
  ckanext/example_theme_docs/v15_fanstatic/templates/base.html
  ckanext/example_theme_docs/v16_initialize_a_javascript_module/fanstatic/webassets.yml
  ckanext/example_theme_docs/v16_initialize_a_javascript_module/templates/snippets/package_item.html
  ckanext/example_theme_docs/v17_popover/fanstatic/webassets.yml
  ckanext/example_theme_docs/v17_popover/templates/snippets/package_item.html
  ckanext/example_theme_docs/v18_snippet_api/fanstatic/webassets.yml
  ckanext/example_theme_docs/v18_snippet_api/templates/snippets/package_item.html
  ckanext/example_theme_docs/v19_01_error/fanstatic/webassets.yml
  ckanext/example_theme_docs/v19_02_error_handling/fanstatic/webassets.yml
  ckanext/example_theme_docs/v20_pubsub/fanstatic/webassets.yml
  ckanext/example_theme_docs/v21_custom_jquery_plugin/fanstatic/webassets.yml
  ckanext/example_theme_docs/v21_custom_jquery_plugin/templates/snippets/package_item.html
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/__init__.py
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/fanstatic/example_theme.js
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/fanstatic/resource.config
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/fanstatic/webassets.yml
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/plugin.py
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/public/promoted-image.jpg
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/templates/base.html
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/templates/home
  ckanext/example_theme_docs/v22_fanstatic_and_webassets/templates/snippets
  ckanext/reclineview/theme/public/resource.config
  ckanext/reclineview/theme/public/webassets.yml
  ckanext/reclineview/theme/templates/recline_view.html
  ckanext/stats/public/ckanext/stats/webassets.yml
  ckanext/stats/templates/ckanext/stats/index.html
  ckanext/textview/tests/test_view.py
  ckanext/textview/theme/public/webassets.yml
  ckanext/textview/theme/templates/text_view.html
  requirements.txt
  setup.py
Labels: Awaiting tech team feedback

#4824 Correctly insert root_path for urls generated with _external flag
  ckan/lib/helpers.py
  ckan/tests/lib/test_helpers.py
Labels: Backport pending

#4820 [#4405] Fix breadcrumb on /datasets
  ckan/templates/package/search.html
Labels: Backport pending
