Repository ckan/ckan, pull requests merged in 2019-07, with the labels that each got.

#4841 Upgrade psycopg2, fixes ckan/ckan#4837
  CHANGELOG.rst
  ckanext/datastore/backend/postgres.py
  requirements.in
  requirements.txt
Labels: Backport 2.8.3, Backport pending

#4843 [#4842] Migrate util controller
  ckan/config/routing.py
  ckan/controllers/util.py
  ckan/templates/snippets/language_selector.html
  ckan/tests/controllers/test_util.py
  ckan/views/util.py
Labels: Flask migration

#4920 #4919 Fix start option in data_dict
  ckan/views/home.py
Labels: Backport pending

#4913 [#4911] Remove test /hello endpoint
  ckan/config/middleware/flask_app.py
  ckan/plugins/toolkit.py
  ckan/tests/config/test_middleware.py
  ckan/tests/test_common.py
  ckanext/example_flask_iblueprint/plugin.py
  ckanext/example_flask_iblueprint/tests/test_routes.py
Labels: Flask migration
