Repository ckan/ckan, pull requests merged in 2019-01, with the labels that each got.

#4599 Fix delete button links
  ckan/templates-bs2/group/member_new.html
  ckan/templates-bs2/organization/member_new.html
  ckan/templates/group/member_new.html
  ckan/templates/organization/member_new.html
Labels: Backport pending

#4630 Check ValueError in url_validator
  ckan/logic/validators.py
  ckan/tests/logic/test_validators.py
Labels: Backport pending

#4591 Script that removes old git branches
  bin/remove-old-git-branches.sh
Labels: Awaiting tech team feedback

#4562 Add a hard upper limit to datastore_search(_sql) rows returned
  CHANGELOG.rst
  ckanext/datastore/backend/postgres.py
  ckanext/datastore/controller.py
  ckanext/datastore/logic/action.py
  ckanext/datastore/logic/schema.py
  ckanext/datastore/tests/test_dump.py
  ckanext/datastore/tests/test_search.py
  doc/maintaining/configuration.rst
  doc/maintaining/datastore.rst
Labels: Awaiting tech team feedback

#2552 2551 Allow a good orthograph for the word 'record' when there is only one result.
  ckanext/reclineview/theme/public/widget.recordcount.js
Labels: Awaiting tech team feedback

#4499 Run CKAN container when db is ready
  contrib/docker/ckan-entrypoint.sh
  contrib/docker/docker-compose.yml
Labels: Awaiting tech team feedback

#4623 Add simple email error logger to flask
  ckan/config/middleware/flask_app.py
Labels: Awaiting tech team feedback

#4641 Remove unused imports from tests
  ckan/tests/controllers/test_api.py
  ckan/tests/controllers/test_organization.py
  ckan/tests/controllers/test_package.py
  ckan/tests/controllers/test_util.py
  ckan/tests/helpers.py
  ckan/tests/legacy/__init__.py
  ckan/tests/legacy/functional/api/base.py
  ckan/tests/legacy/functional/api/model/test_ratings.py
  ckan/tests/legacy/functional/api/model/test_tag.py
  ckan/tests/legacy/functional/api/model/test_vocabulary.py
  ckan/tests/legacy/functional/api/test_activity.py
  ckan/tests/legacy/functional/api/test_api.py
  ckan/tests/legacy/functional/api/test_dashboard.py
  ckan/tests/legacy/functional/api/test_email_notifications.py
  ckan/tests/legacy/functional/api/test_follow.py
  ckan/tests/legacy/functional/api/test_package_search.py
  ckan/tests/legacy/functional/api/test_user.py
  ckan/tests/legacy/functional/api/test_util.py
  ckan/tests/legacy/functional/test_activity.py
  ckan/tests/legacy/functional/test_package.py
  ckan/tests/legacy/functional/test_user.py
  ckan/tests/legacy/lib/test_cli.py
  ckan/tests/legacy/lib/test_dictization.py
  ckan/tests/legacy/lib/test_hash.py
  ckan/tests/legacy/lib/test_tag_search.py
  ckan/tests/legacy/logic/test_action.py
  ckan/tests/legacy/logic/test_auth.py
  ckan/tests/legacy/misc/test_mock_mail_server.py
  ckan/tests/legacy/misc/test_sync.py
  ckan/tests/legacy/models/test_package_relationships.py
  ckan/tests/legacy/models/test_resource.py
  ckan/tests/legacy/models/test_revision.py
  ckan/tests/legacy/test_coding_standards.py
  ckan/tests/lib/search/test_index.py
  ckan/tests/lib/test_navl.py
  ckan/tests/logic/action/test_patch.py
  ckan/tests/logic/test_conversion.py
  ckan/tests/model/test_system_info.py
Labels: Pylons - Flask migration
