Repository ckan/ckan, pull requests merged in 2019-04, with the labels that each got.

#4702 CLI. Implement `config-tool` command
  ckan/cli/cli.py
  ckan/cli/config_tool.py
Labels: Pylons - Flask migration

#4661 Sort ranking in descending order
  ckanext/datastore/backend/postgres.py
Labels: Backport pending

#4595 [#4594] Allow translation of custom licenses
  ckan/model/license.py
  ckan/tests/model/licenses.v1
  ckan/tests/model/licenses.v2
  ckan/tests/model/test_license.py
Labels: Backport pending

#4703 CLI. Implement `seed` command
  ckan/cli/cli.py
  ckan/cli/seed.py
  ckan/lib/create_test_data.py
Labels: Pylons - Flask migration

#4732 Fix recaptcha
  ckan/lib/captcha.py
  ckan/templates/user/snippets/recaptcha.html
Labels: Pylons - Flask migration

#4731 Provide example of requirements installation without source CKAN installation.
  doc/conf.py
  doc/extensions/tutorial.rst
Labels: Docs
