Repository ckan/ckan, pull requests merged in 2019-11, with the labels that each got.

#5046 Fix wrong _ function reference in user blueprint
  ckan/views/user.py
Labels: Backport 2.8.4, Backport pending

#5051 small ui fixes
  ckan/templates/user/edit_user_form.html
  ckan/templates/user/read_base.html
Labels: Backport 2.6.9, Backport 2.7.7, Backport 2.8.4, Backport pending

#5061 fix server error in new_member page
  ckan/views/group.py
Labels: Backport 2.8.4, Backport pending

#5083 CLI. profile
  ckan/cli/cli.py
  ckan/cli/profile.py
Labels: Flask migration

#5082 CLI. front-end-build
  ckan/cli/cli.py
  ckan/cli/front_end_build.py
Labels: Flask migration

#5081 CLI. jobs
  ckan/cli/cli.py
  ckan/cli/jobs.py
Labels: Flask migration

#5086 CLI. views
  ckan/cli/cli.py
  ckan/cli/views.py
Labels: Flask migration

#5069 [#4801] Transform relative imports into absolute ones
  ckan/controllers/admin.py
  ckan/controllers/package.py
  ckan/lib/cli.py
  ckan/lib/helpers.py
  ckan/lib/navl/dictization_functions.py
  ckan/lib/redis.py
  ckan/lib/search/__init__.py
  ckan/lib/search/index.py
  ckan/model/__init__.py
  ckan/model/activity.py
  ckan/model/core.py
  ckan/model/dashboard.py
  ckan/model/domain_object.py
  ckan/model/follower.py
  ckan/model/group.py
  ckan/model/group_extra.py
  ckan/model/meta.py
  ckan/model/package.py
  ckan/model/package_extra.py
  ckan/model/package_relationship.py
  ckan/model/rating.py
  ckan/model/resource.py
  ckan/model/resource_view.py
  ckan/model/system.py
  ckan/model/system_info.py
  ckan/model/tag.py
  ckan/model/task_status.py
  ckan/model/term_translation.py
  ckan/model/tracking.py
  ckan/model/types.py
  ckan/model/user.py
  ckan/model/vocabulary.py
  ckan/plugins/__init__.py
  ckan/plugins/core.py
Labels: Python 3, WIP

#5094 [#4800] Remove formencode support
  ckan/config/environment.py
  ckan/lib/navl/dictization_functions.py
  ckan/tests/legacy/lib/test_navl.py
  ckan/tests/lib/test_navl.py
  doc/extensions/adding-custom-fields.rst
Labels: Python 3

#5104 [#4801] Replace usage of iteritems() with six.iteritems()
  ckan/authz.py
  ckan/cli/translation.py
  ckan/config/middleware/__init__.py
  ckan/config/middleware/flask_app.py
  ckan/controllers/package.py
  ckan/i18n/check_po_files.py
  ckan/lib/base.py
  ckan/lib/dictization/__init__.py
  ckan/lib/dictization/model_dictize.py
  ckan/lib/dictization/model_save.py
  ckan/lib/helpers.py
  ckan/lib/i18n.py
  ckan/lib/lazyjson.py
  ckan/lib/navl/dictization_functions.py
  ckan/lib/navl/validators.py
  ckan/lib/search/index.py
  ckan/logic/__init__.py
  ckan/logic/action/__init__.py
  ckan/logic/action/update.py
  ckan/logic/converters.py
  ckan/migration/revision_legacy_code.py
  ckan/tests/controllers/test_template.py
  ckan/tests/legacy/test_coding_standards.py
  ckan/tests/test_common.py
  ckan/views/api.py
  ckan/views/dataset.py
  ckan/views/feed.py
  ckan/views/group.py
  ckan/views/resource.py
  ckanext/datastore/backend/postgres.py
  ckanext/multilingual/plugin.py
  ckanext/reclineview/plugin.py
  ckanext/textview/plugin.py
Labels: Python 3

#5080 Migrate User CLI
  ckan/cli/cli.py
  ckan/cli/user.py
Labels: Flask migration

#5085 CLI. sysadmin
  ckan/cli/cli.py
  ckan/cli/sysadmin.py
Labels: Flask migration
