Repository ckan/ckan, pull requests merged in 2019-03, with the labels that each got.

#4666 Increase size of h1 headings to 1.8em
  ckan/public-bs2/base/less/ckan.less
  ckan/public/base/less/ckan.less
Labels: Backport pending

#4672 Fix broken block / div nesting in the user/read_base template
  ckan/templates/user/read_base.html
Labels: Backport pending

#4662 Fix hardcoded root paths
  ckan/controllers/user.py
  ckan/views/user.py
Labels: Backport pending

#4509 Allow chaining off core actions
  ckan/logic/__init__.py
  ckanext/datastore/tests/test_chained_action.py
Labels: Awaiting tech team feedback

#4701 CLI. Implement `translation` command
  ckan/cli/cli.py
  ckan/cli/translation.py
Labels: Pylons - Flask migration
