Repository ckan/ckan, pull requests merged in 2019-06, with the labels that each got.

#4838 Make reorder resources button translatable
  ckan/public/base/javascript/modules/resource-reorder.js
Labels: Backport pending

#4489 Correctly handles site_root in Flask requests
  ckan/config/middleware/flask_app.py
  ckan/tests/lib/test_helpers.py
Labels: Awaiting tech team feedback, Backport pending

#4854 Blueprint name is 'feeds' not 'feed'
  ckan/templates/organization/snippets/feeds.html
Labels: Backport pending

#4879 [#4878] Allow custom CKAN callback URL for the DataPusher
  ckanext/datapusher/logic/action.py
  ckanext/datapusher/tests/test.py
  doc/maintaining/configuration.rst
Labels: Backport 2.8.3, Backport pending

#4873 [#4872] Remove _external query param on Pylons generated URLs
  ckan/lib/helpers.py
  ckan/tests/lib/test_helpers.py
Labels: Backport 2.8.3, Backport pending

#4875 [#4874] Allow to provide a custom DataProxy URL
  ckanext/reclineview/plugin.py
  ckanext/reclineview/theme/public/recline_view.js
  ckanext/reclineview/theme/templates/recline_view.html
  doc/maintaining/configuration.rst
Labels: Backport 2.8.3, Backport pending
