Repository ckan/ckan, pull requests merged in 2020-10, with the labels that each got.

#5648 Remove jinja2 blocks from robots.txt
  ckan/public/robots.txt
Labels: Backport 2.9.1, Backport pending

#5644 [#5620] Fix managing resources by collaborators
  ckan/logic/validators.py
  ckan/tests/logic/action/test_create.py
  ckan/tests/logic/action/test_delete.py
  ckan/tests/logic/action/test_update.py
Labels: Backport 2.9.1, Backport pending

#5654 [#5637] package_revise: allow use by normal users
  ckan/logic/action/update.py
  ckan/tests/logic/action/test_update.py
Labels: Backport 2.9.1, Backport pending

#5647 config-tool can be used with incomplete config file
  ckan/cli/cli.py
Labels: Backport 2.9.1, Backport pending

#5645 Use actual default timeout for background jobs
  ckan/lib/jobs.py
  ckan/tests/lib/test_jobs.py
Labels: Backport 2.9.1, Backport pending

#5573 [#5562] Fix KeyErrors in change list detection
  ckan/lib/changes.py
  ckan/tests/lib/test_changes.py
Labels: Backport 2.9.1, Backport pending

#5482 [#5479] Fixed Activity stream on bulk update
  ckan/logic/action/update.py
  ckan/tests/logic/action/test_update.py
Labels: Backport 2.7.9, Backport 2.8.6, Backport 2.9.1, Backport pending

#5639 reloader option fixed
  ckan/cli/server.py
Labels: Backport 2.9.1, Backport pending

#5640 [#5259] Allow IAuthenticator methods to return responses
  ckan/config/middleware/flask_app.py
  ckan/plugins/interfaces.py
  ckan/views/__init__.py
  ckan/views/user.py
  ckanext/example_iauthenticator/__init__.py
  ckanext/example_iauthenticator/plugin.py
  ckanext/example_iauthenticator/tests/test_example_iauthenticator.py
  setup.py
Labels: Backport 2.8.6, Backport 2.9.1, Backport pending

#5604 [#5578] Fix datatablesview filtered-download
  ckanext/datatablesview/blueprint.py
Labels: Backport 2.9.1, Backport pending
