Repository ckan/ckan, pull requests merged in 2020-07, with the labels that each got.

#5463 Fix link to a primer page in documentation
  doc/theming/templates.rst
Labels: Backport 2.6.10, Backport 2.7.8, Backport 2.8.5, Backport pending

#5475 revise improvements
  changes/4618.feature
  ckan/lib/navl/dictization_functions.py
  ckan/logic/action/update.py
  ckan/logic/validators.py
Labels: Backport 2.9.0, Backport pending

#5342 fix order_by param in user_list action
  ckan/logic/action/get.py
  ckan/tests/logic/action/test_get.py
Labels: Backport 2.7.8, Backport 2.8.5, Backport pending

#5358 Type in templates
  ckan/plugins/interfaces.py
  ckan/views/dataset.py
  ckan/views/group.py
  ckanext/example_idatasetform/plugin_v7.py
  ckanext/example_idatasetform/templates/first/new.html
  ckanext/example_idatasetform/templates/first/read.html
  ckanext/example_idatasetform/templates/second/read.html
  ckanext/example_idatasetform/tests/test_example_idatasetform.py
  setup.py
Labels: Backport 2.9.0, Backport pending

#5488 [#5146] Make creation of API keys configurable
  ckan/authz.py
  ckan/config/deployment.ini_tmpl
  ckan/model/user.py
  ckan/tests/model/test_user.py
  ckan/tests/test_coding_standards.py
  doc/api/index.rst
  doc/maintaining/configuration.rst
  test-core.ini
Labels: Backport 2.9.0, Backport pending

#5496 Ignore metadata_modified during revision migration
  ckan/migration/revision_legacy_code.py
Labels: Backport 2.9.0, Backport pending

#5502 [#5501] Remove line breaks and whitespace from translatable strings
  ckan/logic/validators.py
  ckan/templates/snippets/changes/author_email.html
  ckan/templates/snippets/changes/extension_fields.html
  ckan/templates/snippets/changes/extra_fields.html
  ckan/templates/snippets/changes/license.html
  ckan/templates/snippets/changes/maintainer.html
  ckan/templates/snippets/changes/maintainer_email.html
  ckan/templates/snippets/changes/notes.html
  ckan/templates/snippets/changes/org.html
  ckan/templates/snippets/changes/resource_desc.html
  ckan/templates/snippets/changes/resource_extras.html
  ckan/templates/snippets/changes/resource_format.html
  ckan/templates/snippets/changes/resource_name.html
  ckan/templates/snippets/changes/version.html
Labels: Backport 2.9.0, Backport pending

#5506 [uwsgi] set uwsgi buffer size from 4096 to 32768
  ckan-uwsgi.ini
Labels: Backport 2.9.0, Backport pending

#5516 Support ckan.ini by default in the CLI
  ckan/cli/__init__.py
Labels: Backport 2.9.0, Backport pending

#5515 Set host based on site_url on middleware
  ckan/config/middleware/common_middleware.py
Labels: Backport 2.7.8, Backport 2.8.5, Backport 2.9.0, Backport pending

#5520 DataPusher fixes for 2.9
  ckanext/datapusher/logic/action.py
Labels: Backport 2.9.0, Backport pending
