Repository ckan/ckan, pull requests merged in 2020-03, with the labels that each got.

#5196 Fix broken import of OrderdDict
  ckan/controllers/group.py
  ckan/controllers/package.py
Labels: Python 3

#5271 [#5254] show error in text view if xhr failed
  ckanext/textview/theme/public/text_view.js
Labels: Backport 2.6.9, Backport 2.7.7, Backport 2.8.4, Backport pending

#5064 fix code injection in autocomplete module
  ckan/public/base/javascript/modules/autocomplete.js
Labels: Backport 2.6.9, Backport 2.7.7, Backport 2.8.4, Backport pending, WIP

#5167 [#2713] Fix IFacet group customization
  ckan/controllers/group.py
  ckan/controllers/organization.py
  ckan/views/group.py
Labels: Backport 2.6.9, Backport 2.7.7, Backport 2.8.4, Backport pending
