Repository ckan/ckan, pull requests merged in 2020-11, with the labels that each got.

#5714 ensure HTTP_HOST is bytes under python2
  ckan/config/middleware/common_middleware.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5712 Remove old Pylons controllers and routing (and with it, support for Python 2)
  .circleci/config.yml
  .travis.yml
  ckan/config/environment.py
  ckan/config/routing.py
  ckan/controllers/__init__.py
  ckan/controllers/admin.py
  ckan/controllers/api.py
  ckan/controllers/error.py
  ckan/controllers/feed.py
  ckan/controllers/group.py
  ckan/controllers/home.py
  ckan/controllers/organization.py
  ckan/controllers/package.py
  ckan/controllers/user.py
  ckan/tests/legacy/test_coding_standards.py
  ckan/tests/test_coding_standards.py
  setup.py
Labels: Python 3

#5699 [#5698] Filter activities from user at the database level
  changes/5699.bugfix
  ckan/logic/action/get.py
  ckan/model/activity.py
  ckan/tests/controllers/test_package.py
  ckan/tests/logic/action/test_get.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5735 Documentation: Update upgrade_source.rst
  doc/maintaining/upgrading/upgrade-source.rst
Labels: Backport 2.9.2, Backport pending

#5737 [#5731] Add a PluginImplementations wrapper to maintain ordering
  ckan/plugins/core.py
  ckan/tests/plugins/test_core.py
Labels: Backport 2.9.2, Backport pending

#5738 [#5726] Include requirements files in Manifest
  MANIFEST.in
Labels: Backport 2.9.2, Backport pending
