Repository ckan/ckan, pull requests merged in 2020-01, with the labels that each got.

#5141 Remove ckan/websetup.py (legacy pylons testing)
  ckan/tests/legacy/__init__.py
  ckan/tests/legacy/test_coding_standards.py
  ckan/tests/test_coding_standards.py
  ckan/websetup.py
Labels: Cleanup

#5153 [#5152] Fix wrong resource URL after ValidationErrors
  ckan/public/base/css/fuchsia.css
  ckan/public/base/css/green.css
  ckan/public/base/css/main.css
  ckan/public/base/css/maroon.css
  ckan/public/base/css/red.css
  ckan/public/base/javascript/modules/image-upload.js
  ckan/public/base/less/forms.less
  ckan/templates/macros/form.html
  ckan/tests/controllers/test_user.py
  ckan/views/resource.py
Labels: Backport pending

#4923 fix preview button error in EditResouceView page
  ckan/views/resource.py
Labels: Backport 2.6.9, Backport 2.7.7, Backport 2.8.4, Backport pending
