Repository ckan/ckan, pull requests merged in 2020-08, with the labels that each got.

#5511 Installation documenation changes for 2.9
  doc/conf.py
  doc/maintaining/datastore.rst
  doc/maintaining/email-notifications.rst
  doc/maintaining/filestore.rst
  doc/maintaining/getting-started.rst
  doc/maintaining/installing/index.rst
  doc/maintaining/installing/install-from-package.rst
  doc/maintaining/installing/install-from-source.rst
  doc/maintaining/installing/postgres.rst
  doc/maintaining/installing/solr.rst
  doc/maintaining/upgrading/upgrade-package-to-minor-release.rst
  doc/maintaining/upgrading/upgrade-package-to-patch-release.rst
  doc/maintaining/upgrading/upgrade-postgres.rst
  doc/maintaining/upgrading/upgrade-source.rst
  doc/maintaining/upgrading/upgrade-to-python3.rst
Labels: Backport 2.9.0

#5546 Correctly unflatten extras
  ckan/logic/converters.py
  ckanext/example_idatasetform/plugin_v5.py
  ckanext/example_idatasetform/tests/test_example_idatasetform.py
Labels: Backport pending

#5554 Update supervisor-ckan-worker.conf
  ckan/config/supervisor-ckan-worker.conf
Labels: Backport 2.9.1, Backport pending

#5556 Fix skip to content link hiding on screen readers
  ckan/templates/page.html
Labels: Backport 2.8.6, Backport 2.9.1, Backport pending

#5552 Fixes fullscreen for resource webpageview
  ckanext/webpageview/theme/templates/webpage_view.html
Labels: Backport 2.7.9, Backport 2.8.6, Backport 2.9.1, Backport pending

#5535 PackageSearchIndex.index_package(): catch IndexError from date parsing
  ckan/lib/search/index.py
Labels: Backport 2.7.9, Backport 2.8.6, Backport 2.9.1, Backport pending
