Repository ckan/ckan, pull requests merged in 2020-06, with the labels that each got.

#5412 Fix dashboard follower filter
  ckan/public/base/javascript/modules/dashboard.js
  ckan/templates/ajax_snippets/dashboard.html
  cypress/integration/modules/dashboard.spec.js
Labels: Backport 2.8.5, Backport pending

#5420 rtl fixes: homepage search button + layout1
  ckan/public/base/css/main-rtl.css
  ckan/public/base/less/ckan-rtl.less
Labels: Backport 2.7.8, Backport 2.8.5, Backport pending

#5424 [#5401] fix dashboard activity filter
  ckan/views/dashboard.py
Labels: Backport 2.7.8, Backport 2.8.5, Backport pending

#5444 [#5443] unflatten allow nesting >1 level
  ckan/lib/navl/dictization_functions.py
  ckan/tests/legacy/lib/test_navl.py
Labels: Backport 2.6.10, Backport 2.7.8, Backport 2.8.5, Backport pending

#5433 [#5396] res additional info: check res format before res mimetype
  ckan/templates/package/resource_read.html
  ckan/templates/package/resources.html
Labels: Backport 2.6.10, Backport 2.7.8, Backport 2.8.5, Backport pending

#5453 [#5452] allow lists in resource extras
  ckan/lib/dictization/model_save.py
  ckan/logic/schema.py
  ckan/logic/validators.py
  ckan/tests/logic/action/test_create.py
Labels: Backport 2.6.10, Backport 2.7.8, Backport 2.8.5, Backport pending

#5454 Only add error to tag_errors if not empty
  ckan/logic/__init__.py
Labels: Backport 2.6.10, Backport 2.7.8, Backport 2.8.5, Backport pending

#5449 Do not ignore ckan.i18n_directory in flask
  changes/5436.bugfix
  ckan/config/middleware/flask_app.py
  ckan/lib/i18n.py
  ckan/tests/lib/_i18n_dummy_es/i18n/es/LC_MESSAGES/ckan.mo
  ckan/tests/lib/_i18n_dummy_es/i18n/es/LC_MESSAGES/ckan.po
  ckan/tests/lib/test_i18n.py
Labels: Backport 2.8.5, Backport pending

#5470 add class dropdown to 'New view' menu
  ckan/templates/package/resource_views.html
  ckan/templates/package/snippets/resource_info.html
Labels: Backport 2.8.5, Backport pending
