Repository ckan/ckan, pull requests merged in 2021-03, with the labels that each got.

#5923 Update include_users documentation on group_show and organization_show.
  ckan/logic/action/get.py
Labels: Backport 2.9.2, Backport pending

#5926 fix: replace nonexistent UWSGI option "guid" with "gid"
  ckan-uwsgi.ini
  doc/maintaining/installing/deployment.rst
Labels: Backport 2.9.2, Backport pending

#5929 CKAN 2.8 Dockerfile: pin pip version to lower than 21 where python2 is still supported
  Dockerfile
Labels: Backport 2.8.8

#5930 Allow package activity migration on py3
  ckan/migration/migrate_package_activity.py
Labels: Backport 2.9.3, Backport pending

#5937 #5932 fix sqlalchemy configuration, add doc
  ckan/config/environment.py
  doc/maintaining/configuration.rst
Labels: Backport 2.9.3, Backport pending

#5939 Support for setting host and port in the ini file
  ckan/cli/server.py
  ckan/config/deployment.ini_tmpl
  doc/maintaining/configuration.rst
Labels: Backport 2.9.3, Backport pending

#5861 remove unused var in task_status_update
  ckan/logic/action/update.py
Labels: Backport 2.7.11, Backport 2.8.8, Backport 2.9.3, Backport pending

#5969 Make datastore search whitelist case insensitive
  ckanext/datastore/backend/postgres.py
  ckanext/datastore/tests/allowed_functions.txt
  ckanext/datastore/tests/test_search.py
  test-core.ini
Labels: Backport 2.7.11, Backport 2.8.8, Backport 2.9.3, Backport pending

#5995 Include extra files into ckanext distribution
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/MANIFEST.in
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/ckanext/{{cookiecutter.project_shortname}}/assets/webassets.yml
Labels: Backport 2.9.3, Backport pending

#5996 [#5965] Ensure order of plugins in PluginImplementations
  ckan/lib/search/__init__.py
  ckan/plugins/core.py
  ckan/tests/plugins/test_core.py
  setup.py
Labels: Backport 2.9.3, Backport pending
