Repository ckan/ckan, pull requests merged in 2021-05, with the labels that each got.

#5987 Allow to set path to INI file in the WSGI script
  wsgi.py
Labels: Backport 2.9.3, Backport pending

#6063 Reset to first page when adding column filters
  ckanext/datatablesview/public/datatablesview.js
Labels: Backport 2.9.3, Backport pending

#5911 Display propper message when sysadmin password is incorect
  ckan/views/user.py
Labels: Backport 2.8.8, Backport 2.9.3, Backport pending

#6058 Allow utf-8 in resource_formats.json (issue #6054)
  ckan/lib/helpers.py
Labels: Backport 2.8.8, Backport 2.9.3, Backport pending

#6076 [#6006] Fix auth error when deleting a group/org
  ckan/tests/controllers/test_group.py
  ckan/views/group.py
Labels: Backport 2.7.11, Backport 2.8.8, Backport 2.9.3

#6056 Catch TypeError from invalid dates thrown by dateutils
  ckan/lib/search/index.py
  ckan/tests/lib/search/test_index.py
Labels: Backport 2.7.11, Backport 2.8.8, Backport 2.9.3, Backport pending

#6084 Pagination removes repeated params
  changes/6084.bugfix
  ckan/tests/controllers/test_package.py
  ckan/views/dataset.py
  ckan/views/group.py
Labels: Backport 2.9.3, Backport pending
