Repository ckan/ckan, pull requests merged in 2021-01, with the labels that each got.

#5804 Update dashboard.html
  ckan/templates/user/dashboard.html
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5800 Update references to DataPusher documentation
  doc/maintaining/datastore.rst
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5797 Update extension template
  contrib/cookiecutter/ckan_extension/.travis.yml
  contrib/cookiecutter/ckan_extension/LICENSE
  contrib/cookiecutter/ckan_extension/README.md
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/.github/workflows/test.yml
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/.travis.yml
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/README.md
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/README.rst
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/bin/travis-build.bash
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/bin/travis-run.sh
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/ckanext/{{cookiecutter.project_shortname}}/tests/test_plugin.py
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/dev-requirements.txt
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/setup.py
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/test.ini
  doc/contributing/release-process.rst
Labels: Backport 2.9.2, Backport pending

#5782 Fix JavaScript error on Edge
  ckan/public/base/javascript/view-filters.js
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5707 Fix 5705: Cannot update group's image_url field
  ckan/logic/action/update.py
  ckan/tests/logic/action/test_update.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5700 Remove 'paster' occurrences and replace with 'ckan'
  doc/extensions/translating-extensions.rst
  doc/maintaining/cli.rst
  doc/maintaining/tracking.rst
  doc/theming/templates.rst
Labels: Backport 2.9.2, Backport pending

#5734 Add allow_partial_update to fix losing users in group and organization patch actions
  ckan/logic/action/patch.py
  ckan/tests/logic/action/test_patch.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5693 Set default group_type to group in group_create
  ckan/logic/action/create.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5815 [#5814] textview: escape text formats
  ckanext/textview/theme/public/text_view.js
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5827 Fix upload log activity sorting
  ckanext/datapusher/templates-bs2/datapusher/resource_data.html
  ckanext/datapusher/templates/datapusher/resource_data.html
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5839 Update bootstrap.less to reflect correct version
  ckan/public/base/less/bootstrap.less
Labels: Backport 2.8.7, Backport 2.9.2, Backport pending

#5837 [#5836] plugin template and public dirs fix
  ckan/plugins/toolkit.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5830 [#5789] Fix exception when passing limit to organization_list
  ckan/logic/action/get.py
  ckan/tests/logic/action/test_get.py
Labels: Backport 2.7.10, Backport 2.8.7, Backport 2.9.2, Backport pending

#5852 Update install-from-source.rst
  doc/maintaining/installing/install-from-source.rst
Labels: Backport pending
