Repository ckan/ckan, pull requests merged in 2021-09, with the labels that each got.

#6283 Fix runaway preview height
  ckan/public/base/javascript/modules/data-viewer.js
Labels: Backport pending, Backport 2.7.12, Backport 2.8.9, Backport 2.9.4

#6099 cast query string keys/values to string before passing to `quote()`
  ckan/lib/helpers.py
  ckan/tests/lib/test_helpers.py
Labels: Backport pending, Backport 2.9.4

#6110 patch for the issue 6045 "Plugin order for translations is reversed"
  ckan/config/middleware/flask_app.py
Labels: Backport pending, Backport 2.9.4

#6271 [#6051] Allow UTF-8 in JS translations
  ckan/lib/i18n.py
  ckan/views/api.py
Labels: Backport pending, Backport 2.8.9, Backport 2.9.4

#6368 fixing access atom feed for a deleted organization
  ckan/views/feed.py
Labels: Backport pending, Backport 2.7.12, Backport 2.8.9, Backport 2.9.4

#6149 Fix object list validation output
  ckan/lib/navl/dictization_functions.py
  ckan/tests/lib/navl/test_dictization_functions.py
Labels: Backport pending, Backport 2.9.4

#6384 tracking.js module prevent links to be opened in new tabs
  ckan/public/base/javascript/tracking.js
Labels: Backport pending, Backport 2.7.12, Backport 2.8.9, Backport 2.9.4

#6387 Show job title on job start/finish log messages
  ckan/lib/jobs.py
Labels: Backport pending, Backport 2.9.4
