Repository ckan/ckan, pull requests merged in 2021-08, with the labels that each got.

#6325 Update ckan (paster) commands for ckan 2.9.x
  doc/maintaining/installing/install-from-docker-compose.rst
Labels: Backport pending, Backport 2.9.4

#5587 [#5586] Don't cache license translations across requests
  ckan/lib/helpers.py
  ckan/model/license.py
Labels: Backport pending, Backport 2.8.9, Backport 2.9.4

#6286 Fixes HTTP basic auth cred handling
  ckan/lib/search/__init__.py
Labels: Backport pending, Backport 2.9.4

#6346 [#6290] prevent unauth user accessing bulk process [test fix]
  ckan/tests/controllers/test_group.py
  ckan/views/group.py
Labels: Backport pending, Backport 2.7.12, Backport 2.8.9, Backport 2.9.4
