Repository ckan/ckan, pull requests merged in 2022-12, with the labels that each got.

#7125 Read ckan.datasets_per_page on group read handler
  ckan/views/group.py
Labels: Backport pending, Backport 2.10.0

#7259 Final update for types: 2022-12 [2.10 backport]
  ckan/lib/i18n.py
  ckanext/datapusher/logic/action.py
  ckanext/datastore/backend/postgres.py
  ckanext/datastore/blueprint.py
  ckanext/stats/stats.py
  package-lock.json
Labels: Backport pending, Backport 2.10.0

#7241 Add ckan user clean command
  changes/7241.feature
  ckan/cli/clean.py
  ckan/cli/cli.py
  ckan/cli/user.py
  ckan/tests/cli/test_clean.py
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7122 package_update performance purge resources approach
  changes/7119.bugfix
  ckan/lib/dictization/model_save.py
Labels: Backport pending, Backport 2.10.0

#7219 package update performance fix with resource purge (backport)
  ckan/lib/dictization/model_save.py
Labels: Backport pending, Backport 2.9.8

#7253 Add entity type to package get_index
  ckan/lib/search/query.py
Labels: Backport pending, Backport 2.10.0

#7274 Fix package_update documentation
  ckan/logic/action/update.py
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7275 Backport test fix to 2.9
  ckan/tests/logic/action/test_get.py
Labels: Backport pending

#7285 Fix imageview icon
  ckanext/imageview/plugin.py
Labels: Backport pending, Backport 2.10.0

#7290 Update reference to Bootstrap version in docs
  ckan/config/config_declaration.yaml
  doc/theming/best-practices.rst
  doc/theming/index.rst
Labels: Backport pending, Backport 2.10.0

#7284 Add side_effect_free to Activity actions
  ckan/logic/__init__.py
  ckanext/activity/logic/action.py
Labels: Backport pending, Backport 2.10.0
