Repository ckan/ckan, pull requests merged in 2022-11, with the labels that each got.

#7167 [#7166] allow plugins to implement old and new method names (fix)
  ckan/plugins/core.py
Labels: Backport pending

#7121 package_update performance backport version
  ckan/lib/dictization/model_save.py
Labels: Backport pending, Backport 2.9.7

#7162 Fix license field display
  changes/7162.bugfix
  ckan/templates/package/snippets/package_basic_fields.html
Labels: Backport pending, Backport 2.10.0

#7163 Update css files for latest frontend dependencies build
  changes/7163.bugfix
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/vendor/bootstrap/scss/_pagination.scss
  ckan/public/base/vendor/bootstrap/scss/mixins/_grid.scss
Labels: Backport pending, Backport 2.10.0

#7169 Fix activity stream icons
  changes/7169.bugfix
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/scss/_activity.scss
  ckan/public/base/scss/_ckan.scss
  ckan/public/base/scss/_variables.scss
  ckanext/activity/assets/activity.css
  ckanext/activity/assets/activity.css.map
  ckanext/activity/assets/activity.scss
  ckanext/activity/assets/webassets.yml
  ckanext/activity/plugin.py
  ckanext/activity/public/dotted.png
  ckanext/activity/templates/base.html
  ckanext/activity/templates/snippets/activities/added_tag.html
  ckanext/activity/templates/snippets/activities/changed_group.html
  ckanext/activity/templates/snippets/activities/changed_organization.html
  ckanext/activity/templates/snippets/activities/changed_package.html
  ckanext/activity/templates/snippets/activities/changed_resource.html
  ckanext/activity/templates/snippets/activities/changed_user.html
  ckanext/activity/templates/snippets/activities/deleted_group.html
  ckanext/activity/templates/snippets/activities/deleted_organization.html
  ckanext/activity/templates/snippets/activities/deleted_package.html
  ckanext/activity/templates/snippets/activities/deleted_resource.html
  ckanext/activity/templates/snippets/activities/fallback.html
  ckanext/activity/templates/snippets/activities/follow_dataset.html
  ckanext/activity/templates/snippets/activities/follow_group.html
  ckanext/activity/templates/snippets/activities/follow_user.html
  ckanext/activity/templates/snippets/activities/new_group.html
  ckanext/activity/templates/snippets/activities/new_organization.html
  ckanext/activity/templates/snippets/activities/new_package.html
  ckanext/activity/templates/snippets/activities/new_resource.html
  ckanext/activity/templates/snippets/activities/new_user.html
  ckanext/activity/templates/snippets/activities/removed_tag.html
  ckanext/activity/templates/snippets/stream.html
Labels: Backport pending, Backport 2.10.0

#7139 Use API Tokens in Datapusher
  changes/7139.migration
  ckan/tests/cli/test_config.py
  ckanext/datapusher/config_declaration.yaml
  ckanext/datapusher/logic/action.py
  ckanext/datapusher/plugin.py
  ckanext/datapusher/tests/__init__.py
  ckanext/datapusher/tests/test.py
  ckanext/datapusher/tests/test_action.py
  ckanext/datapusher/tests/test_default_views.py
  ckanext/datapusher/tests/test_interfaces.py
  ckanext/datapusher/tests/test_views.py
  ckanext/datastore/tests/test_dictionary.py
Labels: Backport pending, Backport 2.10.0

#7178 Finish updating from control-label to form-label
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/scss/_forms.scss
  ckan/templates/group/member_new.html
  ckan/templates/organization/member_new.html
  ckan/templates/package/collaborators/collaborator_new.html
  ckan/templates/package/snippets/resource_upload_field.html
  ckanext/datatablesview/templates/datatables/datatables_form.html
  ckanext/example_idatasetform/templates/package/snippets/package_metadata_fields.html
Labels: Backport pending, Backport 2.10.0

#7204 Fix social icons
  ckan/templates-bs3/snippets/social.html
  ckan/templates/snippets/social.html
Labels: Backport pending, Backport 2.10.0

#7191 Fix 404 when selecting the same date in the changes view
  changes/7191.bugfix
  ckanext/activity/views.py
Labels: Backport pending, Backport 2.10.0

#7192 Fix 404 when selecting the same date in the changes view [2.9]
  ckan/views/dataset.py
Labels: Backport 2.9.8

#7201 Fix tag list css class
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/scss/_dataset.scss
  ckan/templates/snippets/tag_list.html
Labels: Backport pending, Backport 2.10.0

#7213 Add defaults to check_ckan_version helper on 2.9
  ckan/lib/helpers.py
Labels: Backport 2.9.8

#7215 Fix typo in search-index command
  doc/maintaining/cli.rst
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7218 Restore resource-icons scss file
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/scss/_ckan.scss
  ckan/public/base/scss/_resource-icons.scss
Labels: Backport pending, Backport 2.10.0

#7216 Remove log warnings about ckan.requests.timeout not being declared
  ckan/lib/captcha.py
  ckan/lib/search/__init__.py
  ckan/model/license.py
  ckanext/datapusher/logic/action.py
  ckanext/resourceproxy/blueprint.py
Labels: Backport pending, Backport 2.10.0

#7210 Change user creation defaults [2.9]
  ckan/authz.py
  ckan/config/deployment.ini_tmpl
  ckan/lib/uploader.py
  ckan/logic/action/create.py
  ckan/tests/controllers/test_user.py
  ckan/tests/legacy/functional/api/test_user.py
  ckan/tests/lib/test_uploader.py
  ckan/tests/logic/action/test_create.py
  ckan/tests/logic/auth/test_create.py
  ckan/tests/pytest_ckan/test_fixtures.py
  ckanext/datastore/tests/test_chained_auth_functions.py
  ckanext/example_itranslation/tests/test_plugin.py
  test-core.ini
Labels: Backport 2.9.8

#7217 Add option to output token value without extra messages
  changes/7217.misc
  ckan/cli/user.py
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7232 Fix "_" override
  ckan/views/group.py
Labels: Backport 2.9.8
