Repository ckan/ckan, pull requests merged in 2022-09, with the labels that each got.

#7055 [2.9] Update psycopg2 to support PostgreSQL 12, #5796
  requirements-py2.in
  requirements-py2.txt
  requirements.in
  requirements.txt
Labels: Backport pending, Backport 2.9.6

#6956 Prevent non-sysadmin users to change their own state
  changes/6956.misc
  ckan/logic/schema.py
  ckan/tests/logic/action/test_update.py
  ckan/views/user.py
Labels: Backport pending, Backport 2.8.11, Backport 2.9.6

#6658 [#6657] Fix not empty validator
  ckan/lib/navl/validators.py
  ckan/tests/lib/navl/test_validators.py
Labels: Backport pending, Backport 2.8.11, Backport 2.9.6

#6519 Use get_action in patch actions to allow custom logic
  changes/6519.bugfix
  ckan/logic/action/patch.py
Labels: Backport pending, Backport 2.8.11, Backport 2.9.6

#6817 Fix theme settings
  changes/6817.bugfix
  ckan/config/config_declaration.yaml
  ckan/lib/app_globals.py
  ckan/lib/helpers.py
  ckan/logic/schema.py
  ckan/templates-bs3/admin/config.html
  ckan/templates-bs3/base.html
  ckan/templates-bs3/macros/autoform.html
  ckan/templates/admin/config.html
  ckan/templates/base.html
  ckan/templates/macros/autoform.html
  ckan/tests/controllers/test_admin.py
  ckan/views/admin.py
  doc/contributing/frontend/templating.rst
  doc/extensions/remote-config-update.rst
Labels: Backport pending, Backport 2.9.6

#6926 Fixes two errors when dealing with an encoded url.
  ckan/lib/helpers.py
  ckan/views/__init__.py
  ckanext/datastore/backend/postgres.py
Labels: Backport pending, Backport 2.9.6

#6685 Fixes incorrectly encoded url current url
  ckan/config/middleware/__init__.py
  ckan/controllers/template.py
  ckan/lib/helpers.py
  ckanext/datastore/backend/postgres.py
Labels: Backport pending, Backport 2.8.11
