Repository ckan/ckan, pull requests merged in 2023-01, with the labels that each got.

#7221 Fix module bundling for 2.10 by updating MANIFEST.in
  MANIFEST.in
  setup.cfg
Labels: Backport pending, Backport 2.10.0

#7110 Enable DateTime to be returned through Actions
  changes/7110.bugfix
  ckan/views/api.py
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7329 Add details about JWT secrets to docs
  ckan/config/config_declaration.yaml
Labels: Backport pending, Backport 2.10.0, Backport 2.9.8

#7347 Clean bs3 css migrated to ckanext-activity.
  ckan/public-bs3/base/css/main-rtl.css
  ckan/public-bs3/base/css/main.css
  ckan/public-bs3/base/scss/_activity.scss
  ckan/public-bs3/base/scss/_ckan.scss
  ckan/public-bs3/base/scss/_forms.scss
Labels: Backport pending, Backport 2.10.0

#7324 Attach the actual config object to Click context
  ckan/cli/cli.py
Labels: Backport pending, Backport 2.10.0

#7299 Make skip content visible
  changes/7194.misc
  ckan/i18n/am/LC_MESSAGES/ckan.po
  ckan/i18n/ar/LC_MESSAGES/ckan.po
  ckan/i18n/bg/LC_MESSAGES/ckan.po
  ckan/i18n/ca/LC_MESSAGES/ckan.po
  ckan/i18n/ckan.pot
  ckan/i18n/cs_CZ/LC_MESSAGES/ckan.po
  ckan/i18n/da_DK/LC_MESSAGES/ckan.po
  ckan/i18n/de/LC_MESSAGES/ckan.po
  ckan/i18n/el/LC_MESSAGES/ckan.po
  ckan/i18n/en_AU/LC_MESSAGES/ckan.po
  ckan/i18n/en_GB/LC_MESSAGES/ckan.po
  ckan/i18n/es/LC_MESSAGES/ckan.po
  ckan/i18n/es_AR/LC_MESSAGES/ckan.po
  ckan/i18n/eu/LC_MESSAGES/ckan.po
  ckan/i18n/fa_IR/LC_MESSAGES/ckan.po
  ckan/i18n/fi/LC_MESSAGES/ckan.po
  ckan/i18n/fr/LC_MESSAGES/ckan.po
  ckan/i18n/gl/LC_MESSAGES/ckan.po
  ckan/i18n/he/LC_MESSAGES/ckan.po
  ckan/i18n/hr/LC_MESSAGES/ckan.po
  ckan/i18n/hu/LC_MESSAGES/ckan.po
  ckan/i18n/id/LC_MESSAGES/ckan.po
  ckan/i18n/is/LC_MESSAGES/ckan.po
  ckan/i18n/it/LC_MESSAGES/ckan.po
  ckan/i18n/ja/LC_MESSAGES/ckan.po
  ckan/i18n/km/LC_MESSAGES/ckan.po
  ckan/i18n/ko_KR/LC_MESSAGES/ckan.po
  ckan/i18n/lt/LC_MESSAGES/ckan.po
  ckan/i18n/lv/LC_MESSAGES/ckan.po
  ckan/i18n/mk/LC_MESSAGES/ckan.po
  ckan/i18n/mn_MN/LC_MESSAGES/ckan.po
  ckan/i18n/my_MM/LC_MESSAGES/ckan.po
  ckan/i18n/nb_NO/LC_MESSAGES/ckan.po
  ckan/i18n/ne/LC_MESSAGES/ckan.po
  ckan/i18n/nl/LC_MESSAGES/ckan.po
  ckan/i18n/pl/LC_MESSAGES/ckan.po
  ckan/i18n/pt_BR/LC_MESSAGES/ckan.po
  ckan/i18n/pt_PT/LC_MESSAGES/ckan.po
  ckan/i18n/ro/LC_MESSAGES/ckan.po
  ckan/i18n/ru/LC_MESSAGES/ckan.po
  ckan/i18n/sk/LC_MESSAGES/ckan.po
  ckan/i18n/sl/LC_MESSAGES/ckan.po
  ckan/i18n/sq/LC_MESSAGES/ckan.po
  ckan/i18n/sr/LC_MESSAGES/ckan.po
  ckan/i18n/sr_Latn/LC_MESSAGES/ckan.po
  ckan/i18n/sv/LC_MESSAGES/ckan.po
  ckan/i18n/th/LC_MESSAGES/ckan.po
  ckan/i18n/tl/LC_MESSAGES/ckan.po
  ckan/i18n/tr/LC_MESSAGES/ckan.po
  ckan/i18n/uk/LC_MESSAGES/ckan.po
  ckan/i18n/uk_UA/LC_MESSAGES/ckan.po
  ckan/i18n/vi/LC_MESSAGES/ckan.po
  ckan/i18n/zh_Hans_CN/LC_MESSAGES/ckan.po
  ckan/i18n/zh_Hant_TW/LC_MESSAGES/ckan.po
  ckan/public-bs3/base/css/main.css
  ckan/public-bs3/base/scss/_ckan.scss
  ckan/templates-bs3/page.html
  ckan/templates/page.html
Labels: Backport pending, Backport 2.10.0

#7271 Update setuptools requirement
  .circleci/config.yml
  .github/workflows/cypress.yml
  .github/workflows/pyright.yml
  .github/workflows/towncrier.yml
  Dockerfile
  MANIFEST.in
  changes/7271.removal
  doc/conf.py
  doc/maintaining/installing/install-from-source.rst
  requirement-setuptools.txt
  requirements-docs.txt
  setup.py
Labels: Backport pending, Backport 2.10.0

#7362 Update DataTables plugin file to avoid JS error
  ckanext/datatablesview/public/vendor/DataTables/dataTables.scrollResize.js
Labels: Backport pending, Backport 2.10.0

#7311 Fix color contrast in dashboard buttons
  changes/7193.misc
  ckanext/activity/assets/activity.css
  ckanext/activity/assets/activity.css.map
  ckanext/activity/assets/activity.scss
  ckanext/activity/templates/snippets/pagination.html
Labels: Backport pending, Backport 2.10.0

#7310 Fix color contrast in dashboard
  ckan/templates/user/dashboard.html
Labels: Backport 2.9.8

#7308 Fix color contrast accessibility in user edit page
  ckan/public/base/css/main-rtl.css
  ckan/public/base/css/main.css
  ckan/public/base/less/bootstrap-variables.less
  ckan/public/base/less/forms.less
Labels: Backport pending, Backport 2.10.0

#7107 Fixes two errors when dealing with an encoded url
  changes/7107.bugfix
  ckan/lib/helpers.py
  ckan/views/__init__.py
  ckanext/datastore/backend/postgres.py
Labels: Backport pending, Backport 2.10.0

#7093 use normal keys for package_revise errors
  changes/5888.bugfix
  ckan/logic/action/update.py
Labels: Backport pending, Backport 2.10.0

#7365 Support configurable CSRF field name in the frontend
  ckan/config/config_declaration.yaml
  ckan/config/middleware/flask_app.py
  ckan/lib/base.py
  ckan/public-bs3/base/javascript/client.js
  ckan/public-bs3/base/javascript/modules/confirm-action.js
  ckan/public/base/javascript/client.js
  ckan/public/base/javascript/modules/confirm-action.js
  ckan/templates-bs3/base.html
  ckan/templates/base.html
  ckan/tests/controllers/test_user.py
  ckan/views/user.py
  ckanext/reclineview/theme/public/vendor/ckan.js/ckan.js
Labels: Backport pending, Backport 2.10.0
