Repository ckan/ckan, pull requests merged in 2023-11, with the labels that each got.

#7804 Fix Possible Member Duplication
  changes/7804.bugfix
  ckan/logic/action/create.py
Labels: Backport pending, Backport 2.10.2

#7881 fix: Allow `None` for `beaker.session.timeout`
  changes/7881.bugfix
  ckan/cli/shell.py
  ckan/config/config_declaration.yaml
  ckan/tests/config/test_sessions.py
Labels: Backport pending, Backport 2.10.2

#7891 [7812]Fix URL validator does not support ":" for specifying ports
  ckan/logic/validators.py
  ckan/tests/logic/test_validators.py
Labels: Backport pending, Backport 2.10.2

#7925 [7915]Fix HTML5 validation fails on resource uploads
  ckan/public/base/javascript/modules/resource-upload-field.js
Labels: Backport 2.10.2

#7905 Fix queries when state is in fq_list
  changes/7905.bugfix
  ckan/lib/search/query.py
Labels: Backport pending, Backport 2.10.2, Backport 2.9.10

#7807 download button for datastore-only resources
  changes/7806.bugfix
  ckan/templates/package/resource_read.html
Labels: Backport pending, Backport 2.10.2

#7944 Views Create CLI Sub-Command Fixes
  changes/7944.bugfix
  ckan/cli/views.py
Labels: Backport pending, Backport 2.10.2

#7658 `required` flag adds `not_empty` validator to option
  changes/7658.feature
  ckan/cli/__init__.py
  ckan/cli/config.py
  ckan/config/config_declaration.yaml
  ckan/config/declaration/option.py
  ckan/plugins/core.py
  ckan/tests/cli/test_user.py
  ckan/tests/config/declaration/test_declaration.py
  ckan/tests/config/declaration/test_option.py
  doc/maintaining/configuration.rst
Labels: Backport pending, Backport 2.10.2

#7947 [#7945] Translate aria-label attributes
  changes/7945.bugfix
  ckan/cli/generate.py
  ckan/public/base/javascript/modules/confirm-action.js
  ckan/public/base/javascript/notify.js
  ckan/templates/header.html
  ckan/templates/package/resource_read.html
  ckan/templates/package/snippets/resource_view.html
  ckanext/datastore/assets/js/api-info.js
Labels: Backport pending, Backport 2.10.2

#7943 Allow custom org types for activities
  changes/7943.bugfix
  ckanext/activity/templates/organization/activity_stream.html
  ckanext/activity/templates/snippets/stream.html
  ckanext/activity/tests/test_views.py
  ckanext/activity/views.py
Labels: Backport pending, Backport 2.10.2

#7099 Local Testing Infrastructure
  .circleci/config.yml
  .gitignore
  changes/7099.changes
  doc/contributing/test.rst
  test-infrastructure/README.md
  test-infrastructure/docker-compose.yml
  test-infrastructure/execute.sh
  test-infrastructure/init_environment.sh
  test-infrastructure/install_deps.sh
  test-infrastructure/run_tests.sh
  test-infrastructure/setup.sh
  test-infrastructure/teardown.sh
Labels: Testing
