Repository ckan/ckan, pull requests merged in 2023-07, with the labels that each got.

#7692 Fix package_revise test
  ckan/tests/logic/action/test_update.py
Labels: Backport pending, Backport 2.10.2

#7693 [#7407] Add Solr 9 support
  changes/7693.feature
  doc/contributing/release-process.rst
  doc/maintaining/installing/solr.rst
Labels: Backport pending, Backport 2.10.2

#7526 Fix splitting of list
  ckan/cli/views.py
Labels: Backport pending, Backport 2.11.0, Backport 2.10.2

#7681 `ckan db upgrade` fixes
  changes/7681.misc
  ckan/config/environment.py
  ckan/migration/migrate_package_activity.py
  ckan/migration/revision_legacy_code.py
Labels: Backport pending, Backport 2.10.2, Backport 2.9.10
