Repository ckan/ckan, pull requests merged in 2023-04, with the labels that each got.

#7528 Restore pagination styles in BS5
  changes/7528.bugfix
  ckan/lib/pagination.py
Labels: Backport pending, Backport 2.10.1

#7485 Fix markdown macros regression
  ckan/public/base/javascript/main.js
  ckan/templates/macros/form/markdown.html
Labels: Backport pending, Backport 2.10.1

#7509 [#7508] Escape names in emails
  changes/7508.bugfix
  ckan/lib/mailer.py
  ckan/tests/lib/test_mailer.py
Labels: Backport pending

#7563 Set session scope for migrate_db_for fixture
  changes/7563.misc
  ckan/tests/pytest_ckan/fixtures.py
Labels: Backport 2.10.1
