Repository ckan/ckan, pull requests merged in 2024-08, with the labels that each got.

#8392 Fix resource proxy download proxy setting
  ckan/config/config_declaration.yaml
  ckanext/resourceproxy/blueprint.py
Labels: Backport dev-v2.11, Backport dev-v2.10

#8398 More lenient line length setting for linting
  .flake8
Labels: To Discuss

#8341 Datatables form UI Improvements
  changes/8341.feature
  ckanext/datatablesview/assets/datatables_view.css
  ckanext/datatablesview/assets/datatablesview_form.js
  ckanext/datatablesview/assets/webassets.yml
  ckanext/datatablesview/templates/datatables/datatables_form.html
Labels: Backport pending

#8264 add missing head_extras block
  ckan/templates/base.html
Labels: Backport dev-v2.11

#8404 Update docs with notices regarding DataPusher and ckanext-scheming
  doc/extensions/adding-custom-fields.rst
  doc/maintaining/datastore.rst
Labels: Backport dev-v2.11, Backport dev-v2.10
