Repository ckan/ckan, pull requests merged in 2024-11, with the labels that each got.

#8510 Add extensions migration directory to Manifest.in
  MANIFEST.in
Labels: Backport pending, Backport dev-v2.11, Backport dev-v2.10

#8507 [#8506] Register pytest plugins as entrypoints
  changes/8507.misc
  ckan/tests/pytest_ckan/fixtures.py
  conftest.py
  pyproject.toml
  setup.cfg
Labels: Backport dev-v2.11, Backport dev-v2.10

#8513 Fix extension generation command (again)
  contrib/cookiecutter/ckan_extension/hooks/post_gen_project.py
Labels: Backport dev-v2.11

#8479 Tracking extension fix for 2.11+
  changes/8447.bugfix
  ckanext/tracking/cli/tracking.py
  ckanext/tracking/middleware.py
  ckanext/tracking/migration/tracking/README
  ckanext/tracking/migration/tracking/alembic.ini
  ckanext/tracking/migration/tracking/env.py
  ckanext/tracking/migration/tracking/script.py.mako
  ckanext/tracking/migration/tracking/versions/6313f7679d5f_migration_scripts_for_tracking.py
  ckanext/tracking/model.py
  doc/maintaining/tracking.rst
Labels: Backport dev-v2.11

#8519 Don't add author email to pyproject.toml if empty
  changes/8519.misc
  contrib/cookiecutter/ckan_extension/{{cookiecutter.project}}/pyproject.toml
Labels: Backport dev-v2.11

#8526 Update solr.rst
  doc/conf.py
  doc/maintaining/installing/solr.rst
Labels: Backport dev-v2.11, Backport dev-v2.10

#8520 Automate publication of ckan package to PyPI
  .github/workflows/publish-pypi.yml
  changes/8520.misc
  doc/contributing/maintenance-tools.rst
Labels: Backport dev-v2.11, Backport dev-v2.10

#8485 8483 fix display of user organizations page if there are no organizations
  changes/8483.bugfix
  ckan/lib/helpers.py
  ckan/templates/user/read_organizations.html
Labels: Backport dev-v2.11

#8484 [8482] Fix permissions for groups_available and organizations_available
  changes/8482.bugfix
  ckan/lib/helpers.py
  ckan/templates/user/read_groups.html
  ckan/templates/user/read_organizations.html
  ckan/templates/user/snippets/info.html
Labels: Backport dev-v2.11

#8538 8537: Only show member_count in a group list item if we have that value
  changes/8537.bugfix
  ckan/templates/group/snippets/group_item.html
Labels: Backport dev-v2.11

#8543 Tracking: Fix error when assigning datetime to Row object
  ckanext/tracking/cli/tracking.py
Labels: Backport dev-v2.11
