Repository ckan/ckan, pull requests merged in 2024-06, with the labels that each got.

#8245 Add extra details for backport action docs
  doc/contributing/maintenance-tools.rst
Labels: Backport dev-v2.11

#8257 Mention new inheritance rules(pyutilib removal) in changelog
  changes/7976.removal
Labels: Backport dev-v2.11

#8259 fix for IClick users and #8221
  ckan/cli/cli.py
Labels: Backport dev-v2.11

#8208 Remove hard requirement on password fields
  changes/8208.misc
  ckan/views/user.py
Labels: Backport dev-v2.11

#8228 User autocomplete by email
  changes/8228.feature
  ckan/logic/action/get.py
  ckan/tests/logic/action/test_get.py
Labels: Backport dev-v2.11

#8270 TableDesigner shows incorrect data-dictionary link for new resource
  ckanext/tabledesigner/templates/package/snippets/resource_upload_field.html
Labels: Backport dev-v2.11

#8268 Default Licenses to "Not Open"
  changes/8268.bugfix
  ckan/model/license.py
Labels: Backport dev-v2.11

#8284 Prevent exception in Datatables view when the `size` field is missing
  changes/8284.bugfix
  ckanext/datatablesview/templates/datatables/datatables_view.html
Labels: Backport dev-v2.11, Backport dev-v2.10

#8261 Group update fails when using name instead of id
  ckan/logic/schema.py
  ckan/tests/logic/action/test_update.py
Labels: Backport dev-v2.11

#8297 Test fix: restore configuration state after environment patches
  ckan/tests/config/test_environment.py
Labels: Backport dev-v2.11

#8277 Set orgs_available in user read_base template
  ckan/templates/user/read_groups.html
  ckan/templates/user/read_organizations.html
Labels: Backport dev-v2.11

#8210 [#8207] Fix exception in `group_list` / `organization_list` when passing the `groups` / `organizations`
  changes/8210.bugfix
  ckan/logic/action/get.py
  ckan/tests/logic/action/test_get.py
Labels: Backport pending, Backport dev-v2.11, Backport 2.10.5

#8298 Explain how to stop authentication process
  ckan/lib/authenticator.py
  ckan/plugins/interfaces.py
  ckanext/example_iauthenticator/plugin.py
  ckanext/example_iauthenticator/tests/test_example_iauthenticator.py
Labels: Backport dev-v2.11
