Repository ckan/ckan, pull requests merged in 2024-03, with the labels that each got.

#8048 Fix Last Modified sort parameter for bulk-process page
  ckan/templates/organization/bulk_process.html
Labels: Backport pending, Backport 2.10.4

#8031 Remove nginx cache as beaker cookies are not cacheable
  doc/maintaining/installing/deployment.rst
Labels: Backport pending

#7899 Backport PR 7839 to v2.9 (DataStore Dump Streaming)
  changes/7839.bugfix
  ckanext/datastore/backend/postgres.py
  ckanext/datastore/blueprint.py
  ckanext/datastore/cli.py
  ckanext/datastore/tests/test_dump.py
  ckanext/datastore/writer.py
Labels: Backport pending, Backport 2.9.10

#8101 Datastore Records Delete Action Fix
  changes/8101.feature
  ckanext/datastore/logic/action.py
Labels: Backport pending

#8095 Get the DEFAULT_FORMATS from the ini file
  ckan/cli/views.py
Labels: Backport pending, Backport 2.9.11

#8053 Allow alternate Solr query parsers via allow list
  changes/8053.misc
  ckan/config/config_declaration.yaml
  ckan/lib/search/query.py
  ckan/tests/lib/search/test_search.py
  requirements.in
  requirements.txt
Labels: Backport pending, Backport 2.10.4, Backport 2.9.11
