Repository ckan/ckan, pull requests merged in 2025-04, with the labels that each got.

#8721 [#8379] Store `session["last_active"]` as an iso string instead of a datetime
  changes/8379.bugfix
  ckan/model/user.py
Labels: Backport dev-v2.10

#8677 [#8668] Add auth function for `recently_changed_packages_activity_list`
  changes/8677.bugfix
  ckanext/activity/logic/auth.py
  ckanext/activity/tests/logic/test_auth.py
Labels: Backport dev-v2.11

#8784 [#8775] Add migration to populate empty permission labels
  changes/8784.bugfix
  ckanext/activity/migration/activity/versions/fab3bfdcf830_populate_permission_labels_column.py
Labels: Backport dev-v2.11

#8782 Fix tabledesigner integration with datatables, fix datatables localisation issues
  changes/8782.bugfix
  ckanext/datatablesview/assets/datatablesview.js
  ckanext/datatablesview/helpers.py
  ckanext/datatablesview/plugin.py
  ckanext/datatablesview/public/datatablesview/i18n
  ckanext/datatablesview/templates/datatables/datatables_view.html
  ckanext/tabledesigner/assets/js/tabledesigner-datatables-buttons.js
  ckanext/tabledesigner/assets/js/tabledesigner-fields.js
  ckanext/tabledesigner/templates/datatables/datatables_view.html
Labels: Backport dev-v2.11

#8807 Remove unsupported legacy API keys from documentation
  changes/8195.bugfix
  doc/api/index.rst
Labels: Backport dev-v2.11, Backport dev-v2.10

#8907 Updated datastore_info input to resource_id matching documentation
  changes/8770.misc
  ckanext/datastore/logic/action.py
  ckanext/datastore/logic/schema.py
  ckanext/datastore/tests/test_info.py
Labels: Backport dev-v2.11, Backport dev-v2.10

#8916 [#8770][2.11] Support resource_id as input in datastore_info
  changes/8907.misc
  ckanext/datastore/logic/action.py
  ckanext/datastore/tests/test_info.py
Labels: Backport dev-v2.10

#8804 Longer default CSRF token timeout setting
  changes/8803.bugfix
  ckan/config/config_declaration.yaml
  ckan/config/middleware/flask_app.py
  ckan/lib/helpers.py
  ckan/tests/lib/test_base.py
Labels: Backport dev-v2.11, Backport dev-v2.10
